server:
  port: 8080
  servlet:
    context-path: /api

spring:

  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      username: default
      password: 123456
      timeout: 60000

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/be
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000
      keepalive-time: 300000
      validation-timeout: 3000
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: "hoangleduchuy@gmail.com"
    password: "txredpmukocabgjs"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Keycloak Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/nckh

# JobRunr
jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    port: 8000

# Keycloak Identity Provider
idp:
  url: http://localhost:8180
  client-id: nckh_app
  client-secret: B9OECHjjg8xgjpwGPHCeC5RUMDZeWPAY
